// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Minhwa",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Minhwa",
            targets: ["AppModule"],
            bundleIdentifier: "kybeen.Minhwa",
            teamIdentifier: "RCM87YWJ79",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibraryAdd(purposeString: "This app requires access to photo library add."),
                .photoLibrary(purposeString: "This app requires access to photo library."),
                .camera(purposeString: "This app requires access to camera.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)